name: Portfolio CI/CD

on:
    push:
        branches:
            - main

jobs:
    projectbuild:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

    dockerbuild:
        runs-on: ubuntu-latest
        needs: projectbuild # Wait for projectbuild

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t portfolio:${{ github.sha }} -t portfolio:latest .

    deploy:
        runs-on: ubuntu-latest
        needs: dockerbuild # Wait for dockerbuild

        steps:
            - name: Deploy to the server
              uses: appleboy/ssh-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_PRIVATE_KEY }}
                script: |
                    # Stop and remove any existing container
                    docker stop portfolio || true
                    docker rm portfolio || true
                    
                    # Copy the Docker image from the GitHub runner to the server
                    docker save portfolio:latest | ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.HOST }} "docker load"
                    
                    # Run the container
                    docker run -d --name portfolio --restart always -p 8081:8081 portfolio:latest
