name: Portfolio CI/CD

on:
    push:
        branches:
            - main

jobs:
    projectbuild:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: build-folder
                path: ./out

    dockerbuild:
        runs-on: ubuntu-latest
        needs: projectbuild # Wait for projectbuild

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download build artifacts
              uses: actions/download-artifact@v3
              with:
                name: build-folder

            - name: Build Docker image
              run: |
                # Ensure the downloaded artifact is in the expected location
                mv build-folder ./out
                docker build -t portfolio:${{ github.sha }} -t portfolio:latest .

            - name: Clean up build folder
              run: |
                # Remove the build folder to clean up after Docker build
                rm -rf ./out

    deploy:
        runs-on: ubuntu-latest
        needs: dockerbuild # Wait

        steps:
            - name: Deploy to the server
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_PRIVATE_KEY }}
                script: |
                    # remove running container
                    docker stop portfolio || true
                    docker rm portfolio || true
                    
                    # Copy image from gitHub runner to the server
                    docker save portfolio:latest | ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.HOST }} "docker load"
                    
                    docker run -d --name portfolio --restart always -p 8081:8081 portfolio:latest
